version: '3'

services:
  ui:
    build:
      context: ./ui/
    volumes:
      - ui:/var/www/ui
    restart: "no"

  wordpress:
    image: library/wordpress:5.7-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data/wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - frontend  #for dev purpose we use a bridged network
    logging:
      driver: journald
    ports:
      - 9090:80

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/wordpress_dev.conf:/etc/nginx/conf.d/wordpress.conf:ro
      - ./data/wordpress:/var/www/html:ro
      - ./wp-content:/var/www/html/wp-content:ro
      - ui:/var/www/ui:ro
    depends_on:
      - wordpress
    networks:
      - frontend
    ports:
      - 80:8082
    logging:
      driver: journald

  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - frontend #for dev purpose we use a bridged network
    logging:
      driver: journald

networks:
  frontend:
    driver: bridge

volumes:
  ui: